// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb32fLaaRRf-TAWCbodmmW2zh8b6t9aSo',
    appId: '1:901700721883:web:3f1b2d1e0ae40be08c40fe',
    messagingSenderId: '901700721883',
    projectId: 'gastro-delivery-24710',
    authDomain: 'gastro-delivery-24710.firebaseapp.com',
    storageBucket: 'gastro-delivery-24710.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB67-LQrGNB3IH0e3w7GquoeT7OjqZNdJw',
    appId: '1:901700721883:android:219c7dc9ea7c3a608c40fe',
    messagingSenderId: '901700721883',
    projectId: 'gastro-delivery-24710',
    storageBucket: 'gastro-delivery-24710.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQz9QCywOfTNvycn3Pb59bXGaLlpZhtqA',
    appId: '1:901700721883:ios:add93e2c7ea9751e8c40fe',
    messagingSenderId: '901700721883',
    projectId: 'gastro-delivery-24710',
    storageBucket: 'gastro-delivery-24710.firebasestorage.app',
    iosBundleId: 'com.proyectodam.gastroDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQz9QCywOfTNvycn3Pb59bXGaLlpZhtqA',
    appId: '1:901700721883:ios:add93e2c7ea9751e8c40fe',
    messagingSenderId: '901700721883',
    projectId: 'gastro-delivery-24710',
    storageBucket: 'gastro-delivery-24710.firebasestorage.app',
    iosBundleId: 'com.proyectodam.gastroDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb32fLaaRRf-TAWCbodmmW2zh8b6t9aSo',
    appId: '1:901700721883:web:8cd5030b38af34d88c40fe',
    messagingSenderId: '901700721883',
    projectId: 'gastro-delivery-24710',
    authDomain: 'gastro-delivery-24710.firebaseapp.com',
    storageBucket: 'gastro-delivery-24710.firebasestorage.app',
  );
}
